# -*- coding: utf-8 -*-
"""tarea 3 progra

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dd0vvQZNFhUPpHOnro9gjKSZWB0F_S5u
"""

#Programa de pedido a domicilio
pedido_total=0
print("Bienvenido al sistema de pedido a domicilio.")
print("1. Pizza - $10 \n 2. Hamburguesa - $8 \n 3. Ensalada - $7 \n 0. Finalizar pedido")

#Menú de opciones
while True:
  pedido=input("Introduce el número de la opción que deseas: ")
  match pedido:
    case "1":
      pedido_total+=10
      print(f"Añadiste pizza a tu pedido.\n Total actual: ${pedido_total}")
    case "2":
      pedido_total+=8
      print(f"Añadiste hamburguesa a tu pedido. \n Total actual: ${pedido_total}")
    case "3":
      pedido_total+=7
      print(f"Añadiste ensalada a tu pedido. \n Total actual: ${pedido_total}")
    case "0":
      print(f"El total de su pedido es: ${pedido_total} \nGracias por su pedido. \n¡Buen provecho!")
      break
    case _:
      print("Sintaxis invalida")

redes=[2, 1.5, 2.5, 3, 1, 4]

def prom(redes):
  medida=len(redes)
  if medida==0:
    return 0
  else:
    mid=sum (redes)//medida
    return mid

print(f"El tiempo promedio diario en redes sociales es de {prom(redes)} horas")