# -*- coding: utf-8 -*-
"""Tarea 2 progra

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-rg4mVISL9FqMgQOWebWGba-883VFFES
"""

#Programa para hacer una conversión de diferentes tipos de unidades a cm
opcion=int(input("teclea 1 para pies a cm, 2 para pulgadas a cm, 3 para yardas a cm:  "))
valor=int(input("teclea el valor a convertir: "))

#Convierte de pies a centimentros
def pies_cm(valor):
  resultado=valor*30.48
  return resultado
#Convierte de pulgadas a centimetos
def pulgadas_cm(valor):
  resultado=valor* 2.54
  return resultado
#Convierte de yardas a centimetros
def yardas_cm(valor):
  resultado=valor*91.44
  return resultado

#Menú de opciones
if opcion==1:
  print(pies_cm(valor))
elif opcion==2:
  print(pulgadas_cm(valor))
elif opcion==3:
  print(yardas_cm(valor))
else:
  print("Error")

if valor<=0:
  print("Error")

score=float(input("Teclea tu calificación (de 0 a 1): "))

def nota(score):
  if score <=0.6:
    print("F")
  elif score>0.6 and score<0.7:
    print("D")
  elif score>=0.7 and score<0.8:
    print("C")
  elif score>=0.8 and score<0.9:
    print("B")
  elif score>0.9:
    print("A")

nota(score)
if score>1:
  print("Error")
elif score<0:
  print("Error")

dias=int(input("¿Cuantos días tiene este año?"))
def es_bisiesto(dias):
  if dias%4==0 and dias%100!=0:
    print("es biciesto")
  else:
    print("no es biciesto")

es_bisiesto(dias)