# -*- coding: utf-8 -*-
"""Tarea 1 progra

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nVtSLcpT_wE23DeJ14rX_OCLA6Xx8fIu
"""

import math
#Mide la cantidad de litros necesarios para pintar una pared
area=float(input("¿Cuantos metros cuadrados mide su pared? "))
pintura_necesaria=float(input("¿Cuantos metros cuadrados se pueden cubrir con un litro de pintura? "))
litros=area/pintura_necesaria
litros=math.ceil(litros)
print("Usted necesitará", litros, "litros")

import math
#Calcula la distancia entre dos puntos usando el teorema de pitagoras
def deci(puntox1, puntox2, puntoy1, puntoy2):
    return math.sqrt(((puntox2-puntox1)**2)+(puntoy2-puntoy1)**2)
puntox1=float(input("¿Cual es x del primer punto? "))
puntoy1=float(input("¿Cual es y del primer punto? "))
puntox2=float(input("¿Cual es x del segundo punto? "))
puntoy2=float(input("¿Cual es y del segundo punto? "))

print(deci(puntox1, puntox2, puntoy1, puntoy2))

import math
#Calcula la diagonal de un rectangulo usando el teorema de pitágoras
def diagonal(lado1, lado2):
  return math.sqrt((math.pow(lado1, 2))+(math.pow(lado2, 2)))
lado1=float(input("¿Cuanto mide el ancho? "))
lado2=float(input("¿Cuanto mide el largo? "))
print(diagonal(lado1, lado2))
